### ISSUE TITLE
DropdownMenu should be attachable to any component passed as children

### ISSUE THREAD

**Issue by francescogior** [buildo/revenge-react-components#9]
Requirements
- `DropdownMenu` (thus `Menu`) should create menu just by `options`
- `children` must be the component which is attached to
- if `children` is just an icon, one can pass an `iconClassName` string as a shortcut (current implementation)

**Comment by FrancescoCioria** [comment]
from these requirements it looks like you're creating a new `Popover`. Couldn't `DropdownMenu` be a simple wrapper of `Popover` from `react-components`?
